/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.controlaccesomuseocompensar;

/**
 *
 * @author Ing. Fernando Gómez
 */
public class FormularioAcceso extends javax.swing.JFrame {
    
    private ControlAccesoMuseoCompensar control;//Se agrega conexión a la otraclase 
    private double tarifa;
   
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(FormularioAcceso.class.getName());

    /**
     * Creates new form FormularioAcceso
     */
    public FormularioAcceso() {
        initComponents();
        
        setFocusTraversalPolicy(new java.awt.FocusTraversalPolicy() {

        @Override
        public java.awt.Component getComponentAfter(
                java.awt.Container container,
                java.awt.Component component) {

            if (component == TxtNombre) {
                return TxtIdentidad;
            } else if (component == TxtIdentidad) {
                return TxtEdad;
            } else if (component == TxtEdad) {
                return CbxCategoria;
            } else if (component == CbxCategoria) {
                return BtnRegistrar;
            } else if (component == BtnRegistrar) {
                return BtnLiquidar;
            } else if (component == BtnLiquidar) {
                return BtnCancelar;
            } else {
                return TxtNombre;
            }
        }

        @Override
        public java.awt.Component getComponentBefore(
                java.awt.Container container,
                java.awt.Component component) {

            if (component == TxtIdentidad) {
                return TxtNombre;
            } else if (component == TxtEdad) {
                return TxtIdentidad;
            } else if (component == CbxCategoria) {
                return TxtEdad;
            } else if (component == BtnRegistrar) {
                return CbxCategoria;
            } else if (component == BtnLiquidar) {
                return BtnRegistrar;
            } else if (component == BtnCancelar) {
                return BtnLiquidar;
            } else {
                return TxtNombre;
            }
        }

        @Override
        public java.awt.Component getFirstComponent(
                java.awt.Container container) {
            return TxtNombre;
        }

        @Override
        public java.awt.Component getLastComponent(
                java.awt.Container container) {
            return BtnCancelar;
        }

        @Override
        public java.awt.Component getDefaultComponent(
                java.awt.Container container) {
            return TxtNombre;
        }
        });
        
        control = new ControlAccesoMuseoCompensar(); //Conexion entre clases
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        TxtNombre = new javax.swing.JTextField();
        TxtIdentidad = new javax.swing.JTextField();
        TxtEdad = new javax.swing.JTextField();
        CbxCategoria = new javax.swing.JComboBox<>();
        Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnRegistrar = new javax.swing.JButton();
        BtnLiquidar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtALiquidacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        TxtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtEdadKeyTyped(evt);
            }
        });

        CbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORÍA A", "CATEGORÍA B", "CATEGORÍA C", "NO AFILIADO" }));
        CbxCategoria.addActionListener(this::CbxCategoriaActionPerformed);

        Titulo.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BIENVENIDO AL MUSEO DE COMPENSAR");

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("A continuación ingrese los datos de los visitantes...");

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(this::BtnCancelarActionPerformed);

        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(this::BtnRegistrarActionPerformed);

        BtnLiquidar.setText("Finalizar Registro");
        BtnLiquidar.addActionListener(this::BtnLiquidarActionPerformed);

        jLabel3.setText("Ingrese los datos, y haga clic en registrar, al finalizar haga clic en finalizar registro para obtener su liquidación.");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("NOMBRE COMPLETO:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("NUMERO DE IDENTIDAD:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("EDAD:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("CATEGORIA DE CAJA DE COMPENSACION:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("VALOR A PAGAR");

        TxtALiquidacion.setEditable(false);
        TxtALiquidacion.setColumns(20);
        TxtALiquidacion.setLineWrap(true);
        TxtALiquidacion.setRows(5);
        jScrollPane1.setViewportView(TxtALiquidacion);

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(BtnRegistrar)
                .addGap(118, 118, 118)
                .addComponent(BtnLiquidar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCancelar)
                .addGap(69, 69, 69))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(88, 88, 88))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(TxtIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(11, 11, 11)
                .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(TxtIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnRegistrar)
                    .addComponent(BtnLiquidar))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void CbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxCategoriaActionPerformed
        // TODO add your handling code here:
        if (TxtEdad.getText().isEmpty()) {
        TxtALiquidacion.setText("Por favor ingrese la edad.");
        return;
        }
        
        int edad = Integer.parseInt(TxtEdad.getText());
        String categoria = CbxCategoria.getSelectedItem().toString();                
        //double tarifa = 0; Se pasa de variable local a objeto.
        
        if(edad < 18){
            tarifa = 5000;
        }else {
            switch (categoria) {
                case "NO AFILIADO":
                    tarifa = 30000;
                    break;
                case "CATEGORÍA A":
                    tarifa = 30000 * 0.85;
                    break;
                case "CATEGORÍA B":
                    tarifa = 30000 * 0.70;
                    break;
                case "CATEGORÍA C":
                    tarifa = 30000 * 0.50;
                    break;
            }
        }
        
        TxtALiquidacion.setText(String.format(
                "El valor a pagar es $%,.2f", tarifa));
    }//GEN-LAST:event_CbxCategoriaActionPerformed

    private void TxtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEdadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

    if (!Character.isDigit(c)) {
        evt.consume();
    }
    }//GEN-LAST:event_TxtEdadKeyTyped

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        // TODO add your handling code here:
        try{
        String nombre = TxtNombre.getText();
        String identidad = TxtIdentidad.getText();
        int edad = Integer.parseInt(TxtEdad.getText());
        String categoria = CbxCategoria.getSelectedItem().toString();
        control.registrarVisitantes(nombre, identidad, edad, categoria, tarifa);
        } catch (NumberFormatException e) {

        TxtALiquidacion.setText("Debe diligenciar todos los datos");
        } finally {

        System.out.println("Proceso de registro finalizado.");

        }        
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void BtnLiquidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLiquidarActionPerformed
        // TODO add your handling code here:
        control.exportarVisitantes();
    }//GEN-LAST:event_BtnLiquidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioAcceso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnLiquidar;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JComboBox<String> CbxCategoria;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel Titulo;
    private javax.swing.JTextArea TxtALiquidacion;
    private javax.swing.JTextField TxtEdad;
    private javax.swing.JTextField TxtIdentidad;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}